### ISSUE TITLE
Formatted Date/Time in CSV Export

### ISSUE THREAD

**Issue by ksnell88** [VerusCoin/Verus-Desktop#105]
Requesting the date/time format be updated to something Microsoft Excel or LibreOffice Calc can read and format to a usable date that can be filtered on, imported to other databases, etc. Currently the format is d/m/YYYY h:mm:ss but no spreadsheet software I have tried can read this as anything other than Text, nor do the formatting functions in Excel/Calc work on it.

**Comment by michaeltout** [comment]
Not sure what format excel expects but this commit I just made https://github.com/VerusCoin/Verus-Desktop-GUI/commit/8fb0c362e56ce5a00616e1ee8634f5ccd60cd05b makes the CSV date/time format compliant with ISO 8601, which should make it compatible with most spreadsheet software. I'll leave this issue open until the next release, which will include the fix.

**Comment by ksnell88** [comment]
Thank you! I'll give it a try in the future release. Looking forward to making tax time a bit easier.

**Comment by ksnell88** [comment]
Confirmed on v0.9.2-2 that the new date format is MUCH better in Excel. For anyone coming across this you can do a Find/Replace to replace Z with nothing and T with a space. It will then recognize the field as a date. Thank you for making this improvement!

**Comment by michaeltout** [comment]
Thanks for the report! Glad this fixed the issue.
