### ISSUE TITLE
Windows Installer Deletes all files in the destination Directory!!!!!!!

### ISSUE THREAD

**Issue by xhamma** [VerusCoin/Verus-Desktop#106]
Without warning, the installer deletes all files in the destination directory - included the encrypted folder than contained my private key! And, since it was on a SSD with TRIM, it is gone forever and so is all of my Verus Coin.

Don't do this! And if you do, pause the installer and WARN the user!!! If you are updating, you have a list of files that need to be replaced... you shouldn't be deleting users files!!!!

**Comment by Oink70** [comment]
The Windows installer removes all existing files from the program folder. Verus Desktop does not store **any** user settings (that includes keys) in the program folder. All user settings are stored in the windows user profile folders.

Verus Desktop does not remove any files containing keys or profile settings from the user.

**Comment by xhamma** [comment]
The issue is that I stored files in that folder, and the installer deleted them with no warning. I installed it to a specific location that is secured, not the default path and I had my keys inside an encrypted folder in that path. I don't allow any of my crypto wallets to use the non secured default locations. I accept the fault because I had just started mining this coin a few weeks ago and I hadn't backed up my keys elsewhere, but still - the installer should not assume that a user hasn't stored any files in the directory and it should not delete any files not associated with the installation itself.

**Comment by michaeltout** [comment]
If you're referencing the windows installer cache, it is not recommended to store your files or data there as it is assumed that those folder can be overwritten during an update or removed during an uninstall (automatically). If I am missing something feel free to reopen this issue or elaborate in our discord at http://verus.io/discord.
