### ISSUE TITLE
Cant change data directory

### ISSUE THREAD

**Issue by cafeg** [VerusCoin/Verus-Desktop#12]
In native mode I have tried to change the data directory from the default c:\users\,,,\komodo\vrsc to a directory on another drive as my C:\ SSD only has 10gb free.
I changed it in the GUI config but it still goes to the default directory and tries to put the blockchain in there when downloading it. I also made sure the directory was created and had a fresh bootstrap in it as well but no go.
A suggestion: perhaps asking the user where he wants the data directory on first load of the program as a lot of SSD drives with the op system on these days are small with larger drives outside the SSD.

**Comment by michaeltout** [comment]
Fixed and tested in 0.6.4-beta [here](https://github.com/VerusCoin/Verus-Desktop/commit/03799f9ca8db7fd5c0a16f99856b6315808ac9c3), feel free to reopen if this did not fix the problem for you.
