### ISSUE TITLE
issue cant send zcoin firo

### ISSUE THREAD

**Issue by Joelkc** [VerusCoin/Verus-Desktop#131]
![Sin t1ítulo](https://user-images.githubusercontent.com/92908221/138219804-35f88663-320b-496b-9d6e-11d684ef7995.png)

**Comment by michaeltout** [comment]
This error typically occurs when the funds you are trying to spend aren't confirmed yet. Please go to the Verus discord channel at http://verus.io/discord if the issue persists, a member of the Verus community can help you there.
