### ISSUE TITLE
can't send BCH to address with first letter "q"

### ISSUE THREAD

**Issue by wong-fi-hung** [VerusCoin/Verus-Desktop#135]
why me can't send to other wallet...
and in this case, i have copyed true address and not wrong.
please help me sir... :(

![BCH_PROBLEM](https://user-images.githubusercontent.com/68433096/143667670-cad2036e-e4a2-416c-a6a8-7058f4825d45.png)
Please describe your issue in detail. Attach screenshots if you can, they help a lot.

**Comment by michaeltout** [comment]
At the moment Verus Desktop only supports legacy BCH addresses. Until q-addr support is added, I would recommend looking into the possibility of using an address converter.
