### ISSUE TITLE
unable to send ZEC using lite server

### ISSUE THREAD

**Issue by QuickMythril** [VerusCoin/Verus-Desktop#150]
when i try to send ZEC with transparent addresses using the lite server in Verus Wallet i get this big error which says nothing.  someone said it might be the whole raw transaction posted there.  just a bunch of hex code with a very long scroll bar.

i am able to export the private key of that address, and import it in ZCash wallet, however their Lite wallet does not support importing t-addr by privkey, only the private spending/viewing style.  so i'd have to use the Full node wallet, and at the moment i don't have the space to download the whole chain...

if i knew i would have never mined to the Verus wallet address to start, but i am wondering how i can help to get this problem solved, because that's really not good for people to have their funds stuck like that.  it's definitely enough that i would not consider ZEC to be fully implemented there as it appears.  kind of wondering if i am the only person with this issue.

this appears to have been reported before:
https://github.com/VerusCoin/Verus-Desktop/issues/89

"two days of syncing" is not a solid solution for me...  :D

**Comment by QuickMythril** [comment]
ah it seems with such a large transaction taking many small UTXOs (cause of mining) the actual message of the error was cut off.  (so that is a secondary issue, where too much text cannot be displayed.)
sending a smaller amount still did not work, but it let me see the error:

Status: error
**Error: the transaction was rejected by network rules. 16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)**

**Comment by michaeltout** [comment]
This issue was most likely due to an outdated Zcash consensus branch ID after their hard fork. If this is the case it should no longer occur past v0.9.1. Feel free to reopen this issue if it persists.
