### ISSUE TITLE
5ad194fe8b5a84443d6339e5e88dffe58d95aa6765b083847b223baabf56bb82

### ISSUE THREAD

**Issue by thelongeffect** [VerusCoin/Verus-Desktop#153]
I sent 324 verusn coins to RC68kwhvNtt6xkbe8vN2poXSf5nPY5o8iV. The txid is 5ad194fe8b5a84443d6339e5e88dffe58d95aa6765b083847b223baabf56bb82 . the transaction said it went through, but after 12 hours its not getting any confirmation and I cannot find the transaction on the blockchain.

the_long_effect@yahoo.co
![pic3](https://user-images.githubusercontent.com/84944601/158898321-35856909-3565-493d-b512-af65942940ab.PNG)
![pic2](https://user-images.githubusercontent.com/84944601/158898326-b203002f-f74e-431f-a46b-cbc44d9d11e4.PNG)
![pic1](https://user-images.githubusercontent.com/84944601/158898341-641d7c95-a10e-400d-8e0f-87381497e837.PNG)
![pic1](https://user-images.githubusercontent.com/84944601/158898380-5211dd4b-d09f-4b90-941d-926e74a6b960.PNG)
m

**Comment by Oink70** [comment]
Most likely cause is that you wallet is not synchronized.
Please visit discord (https://verus.io/discord) for assistence.
