### ISSUE TITLE
"No running PIRATE daemon found."

### ISSUE THREAD

**Issue by garnon** [VerusCoin/Verus-Desktop#18]
- Launch Verus desktop 0.6.4-beta and create a new profile from a seed, encrypt it
- add the DEX coin and the pirate coin, both in native mode
- click on one of those added coins

In the upper right corner it says "No running PIRATE daemon found." with a spinning wheel, and it doesn't proceed. It's impossible to add / create addresses.

**Comment by garnon** [comment]
changing the zcash parameter source in the settings and restarting the app doesn't solve the problem.

**Comment by michaeltout** [comment]
Having trouble re-creating, an address creation/display issue for non-z chains (including DEX) was fixed [here](https://github.com/VerusCoin/Verus-Desktop/commit/ecfad896785687267abc4b48e0df38f780ba7cf5), and will be out in an upcoming release, but I cannot re-produce the PIRATE launch issue. I would recommend getting help on our [Discord](https://discord.gg/VRKMP2S) to see if your computer is preventing the blockchain daemon from launching.
