### ISSUE TITLE
DEX coin not available in light mode

### ISSUE THREAD

**Issue by garnon** [VerusCoin/Verus-Desktop#19]
- Add the DEX coin and try to select light mode.

--> the selection doesn't work. 

For standard coins, such as KMD or DEX, light mode should be available (just like in Agama wallet). Only in special z-coins / shielded coins, such as PirateChain, the non availability of the light mode is understandable.

**Comment by michaeltout** [comment]
Should be fixed as of [this](https://github.com/VerusCoin/agama-wallet-lib/pull/16) PR, and will be released with the next version. Also, this case was a bug, but the general availability of lite mode depends on whether or not a coin has working electrum servers, so even in cases where the coin isn't special / z-only, lite mode still may not always be available.
