### ISSUE TITLE
"File" menu missing, debug menu should be called "Help"

### ISSUE THREAD

**Issue by garnon** [VerusCoin/Verus-Desktop#20]
What's missing: A file menu with the possibilty to export the private keys of selected addresses.

What no mainstream user will understand or is too technical: a menu called "debug". Instead, "Help" is more common.

**Comment by michaeltout** [comment]
Just fixed the naming issue [here](https://github.com/VerusCoin/Verus-Desktop/commit/966975364c7a76515358fd68a8a33d7e706f2cb9), and you can currently get the private key of an address by selecting it from your address menu and pressing "copy private key", and export your entire wallet through the in wallet CLI in settings>coin settings. This will be added in an upcoming release in a more intuitive/GUI way. 

Also, thank you for the feedback, but just for future reference, please upload issues/suggestions in separate threads so it is easier to address them independently.
