### ISSUE TITLE
(Minor, GUI-related:) wrong button pressed state, wrong cursor

### ISSUE THREAD

**Issue by garnon** [VerusCoin/Verus-Desktop#21]
When pressing one of the three main navigation tabs / buttons called "Wallet", "Verus Identities", "Mining", there are two graphically wrong picture states:
- state on, mouse over: the blue color should not become inactive/grey, but stay blue.
- state on, mouse down: same observation

Also, sometimes there's the expected mouse pointer curser, while sometimes there's a strange keyboard curser icon when hovering the buttons.

**Comment by michaeltout** [comment]
Thank you for the feedback, the text does turn blue to indicate that the tab is in use on hover, so this is somewhat subjective, but if the general consensus among the community is that it would be nicer to have the tab stay blue, then it can definitely be changed

**Comment by garnon** [comment]
It's simply not how buttons behave anywhere else. When a tab is selected, it is blue instead of grey, great. But this is only visible when you remove the mouse from the button. When you return to the active blue tab, it becomes grey again as soon as you hover. An active button never flips to its inactive color when hovering it.

**Comment by michaeltout** [comment]
Valid points, I've changed it in [this](https://github.com/VerusCoin/Verus-Desktop-GUI/commit/7efd51b4c01d55d230c9a48762d2ada30f0c08be) commit, and this should be rolled out in a future release.
