### ISSUE TITLE
No option for importing a WIF key

### ISSUE THREAD

**Issue by garnon** [VerusCoin/Verus-Desktop#23]
If Verus Desktop is meant to be a replacement for Agama, there should definitely be a WIF key import option e.g. for PirateChain.

**Comment by michaeltout** [comment]
This feature will be implemented in a more intuitive/GUI way in an upcoming release, but for now, importing a WIF key can be done through the CLI in the settings portion of the app, by following this guide (https://wiki.veruscoin.io/#!how-to/how-to_convert-seed-to-wif.md)
