### ISSUE TITLE
ERC20 tokens

### ISSUE THREAD

**Issue by Oink70** [VerusCoin/Verus-Desktop#25]
ERC20 tokens ( eg ETH, BAT, ZRX, REP) are not displayed in Verus Desktop 0.6.4 beta. The balance is empty and there is no transaction history. 

It looks like something has changed on the ETH electrum servers, since the unsupported Verus Agama displays similar issues, showing NaN for balance.

Behaviour is consistent on Linux, MacOS and Windows versions.

**Comment by cryptopoli** [comment]
Auch ChainLink ist betroffen
![chainlink balance 0](https://user-images.githubusercontent.com/38912635/80864767-ff98d800-8c84-11ea-8a77-d89635c9b5bd.png)

**Comment by cryptopoli** [comment]
An update for ERC20 tokens is in prospect soon?

**Comment by crackfoo** [comment]
Can some progress with this issue be made?

**Comment by cryptopoli** [comment]
> Können mit diesem Problem einige Fortschritte erzielt werden?

Concerns, VerusWallet Desktop:
Unfortunately no progress in this matter, ERC20 tokens (chainlink) NaN are not synced.

**Comment by michaeltout** [comment]
Should be fixed [here](https://github.com/VerusCoin/Verus-Desktop/commit/3eda06b4a5c17513546ea3162b59a8ea167de136), and released in the upcoming release. If anyone still has troubles with this issue after that feel free to re-open.

**Comment by cryptopoli** [comment]
Installation Verus-Desktop v 0.5.2 ín the folder of the previous version.
Leave the current wallet dat in VRSC.
Message:
Unexpected token < in JSON at position 0

![vrsC_V6 5 2_2020 05 21_09h43m27s_002_](https://user-images.githubusercontent.com/38912635/82535902-e084bc00-9b47-11ea-92e3-d8c844b7c275.png)

**Comment by crackfoo** [comment]
Same here.... OSX version.

**Comment by cryptopoli** [comment]
ETH/ERC20 Token problem behoben.

**Comment by michaeltout** [comment]
@cryptopoli @crackfoo Both the ERC20 issue and the Unexpected token issue should be resolved in 0.6.5-3, please download [here](https://github.com/VerusCoin/Verus-Desktop/releases/tag/v0.6.5-3) and if an issue persists, feel free a new GitHub issue, rather than commenting on an unrelated one. (regarding the unexpected token problem, not the last comment by @cryptopoli)

**Comment by crackfoo** [comment]
yes, all is working as expected now, thanks!

**Comment by cryptopoli** [comment]
@michaeltout   ERC20 token new problem!   VerusDesk v 6.5-3  token will send with message:  "gas required exceeds allowance (999991) or allways faling transaction"   Acknowledged?    ETH: Receive no result visible?

![chainlink_2020 06 01_15h00m13s_001_](https://user-images.githubusercontent.com/38912635/83421431-63e7bc80-a428-11ea-8950-ccdc63b1c8aa.png)
