### ISSUE TITLE
Entering seed in lite mode

### ISSUE THREAD

**Issue by Oink70** [VerusCoin/Verus-Desktop#27]
People are intuitively clicking the 'Generate a New seed`-button after entering their own seed. Although the text is clear, the arrow to the right in the seed-box is overlooked as the proper way to continue.

Greying out the big blue button and highlighting the arrow, once characters are entered may be a way to make it more intuitive.

**Comment by michaeltout** [comment]
This has been resolved since the rework to the lite mode setup process in 0.9.1
