### ISSUE TITLE
Wrong coin loads

### ISSUE THREAD

**Issue by Oink70** [VerusCoin/Verus-Desktop#32]
When trying to add Pungo in lite mode to the wallet, Puregold Token gets selected and loaded.
When PureGold Token gets selected it loads PureGold Token as intended.

Pungo is not available.

**Comment by Oink70** [comment]
After updating to v0.6.5-2:
No coin is loaded. 

Error message:  `Unexpected token < in JSON at position 0`

**Comment by Oink70** [comment]
1st issue persist in release 0.6.5-3

**Comment by Oink70** [comment]
Original issue persists in release 0.7.1-5

**Comment by michaeltout** [comment]
Fixed in https://github.com/VerusCoin/Verus-Desktop-GUI/commit/e1f2642c6f196158f3564f6bf7652e8d97f2eda8
