### ISSUE TITLE
Lite mode coins don't load in v0.6.5-2

### ISSUE THREAD

**Issue by Oink70** [VerusCoin/Verus-Desktop#36]
After updating to v0.6.5-2:
No lite mode coin can be loaded. 

Error message:  `Unexpected token < in JSON at position 0`

Removing the Verus-Desktop settings folder does **not** solve it.

**Comment by cryptopoli** [comment]
Installation Verus-Desktop v 0.5.2 ín the folder of the previous version.
Leave the current wallet dat in VRSC.
Message:
Unexpected token < in JSON at position 0

**Comment by Oink70** [comment]
Issue resolved in release v0.6.5-3
