### ISSUE TITLE
Allow pubkey specification for daemon launch

### ISSUE THREAD

**Issue by bishop-kmd** [VerusCoin/Verus-Desktop#39]
Can we add a launch parameter to specify a pubkey for mining/staking. Ideally, set it once in the app and then on every launch, the pubkey is passed as a startup argument to the daemon?

**Comment by michaeltout** [comment]
Thanks for the suggestion! This is now available through the "custom native mode launch options" setting in versions 0.7.3 and newer, where you can specify any custom launch parameters for supported native coins
