### ISSUE TITLE
zcoin (XZC) displays electrum connection error

### ISSUE THREAD

**Issue by Oink70** [VerusCoin/Verus-Desktop#63]
*connection error or incomplete data* error shows in the *Blockchain status* section.
Likely the electrums not responding.
server info:
electrumx.zcoin.io:50001:tcp,electrumx01.zcoin.io:50001:tcp,electrumx02.zcoin.io:50001:tcp,electrumx03.zcoin.io:50001:tcp

Which is identical as in the komodo coins list on their github.

**Comment by michaeltout** [comment]
It was an electrum error, it seems they are resolved now.
