### ISSUE TITLE
Komodo reward claiming in Lite mode error in V0.7.1-5

### ISSUE THREAD

**Issue by Oink70** [VerusCoin/Verus-Desktop#64]
When running KMD in Lite mode, both the blue `Unclaimed Interest` button as a regular send of the funds to your own or another address throws up the error: **kpX.umod is not a function**

This error does not exist in previous wallet versions

**Comment by Oink70** [comment]
Update: This issue only seems to be happening in the Windows build. Other Lite mode coin that's been reported to show this error when sending out funds is BTC

**Comment by michaeltout** [comment]
kPx.umod issues should now be completely resolved in v0.7.2-3, anyone can reopen this issue if they reappear
