### ISSUE TITLE
not able to send ZEC

### ISSUE THREAD

**Issue by AlexAlex923** [VerusCoin/Verus-Desktop#65]
I am not able to send 0.0499 ZEC from Verus Desktop to Atomic. 
The error message is below. I am not able to understand where the error is...
Alex

the transaction was rejected by network rules. 16: old-consensus-branch-id (Expected f5b9230b, found 2bb40e60) [0400008085202f890147210d7dd51f052fb3b09d31ac3ed5299e8f6889fbc94cc41e906a29108b6827000000006b483045022100e4c62beb56678ed73959f1abfdfa395e3a9548ebd620a25f36e16412087b5b6f02205cfe8b1b8c6500e2783a9023a1e1e5c29fd5be6b7bfe4de37e1cee4cb752cc28012102f94c384971a330c2a0b67fb92e1b53fb787f858cc0c552c83f1b8033ff217eeeffffffff0120fd4b00000000001976a91442ce6a7201681da91a440d0384916991adc4071088ac00000000000000000000000000000000000000]

**Comment by michaeltout** [comment]
I believe this issue was solved in an iteration of 0.7.2, and it should no longer occur on 0.7.3 and newer, if you experience it again, feel free to reopen this.
