### ISSUE TITLE
not able to send LINK

### ISSUE THREAD

**Issue by AlexAlex923** [VerusCoin/Verus-Desktop#66]
I am not able to send 9.4 LINK (all funds) from Verus Desktop to Atomic. 
Below there is the error message. Please help me to understand. Thank you.
Alex

gas required exceeds allowance (12505966) or always failing transaction

**Comment by michaeltout** [comment]
This should now be resolved in 0.7.3 and newer due to a refactor of the backend ETH/ERC20 code
