### ISSUE TITLE
indentity apis

### ISSUE THREAD

**Issue by icelover3** [VerusCoin/Verus-Desktop#72]
Please describe your issue in detail. Attach screenshots if you can, they help a lot.

**Comment by icelover3** [comment]
Identity APIs not activated on blockchain.

**Comment by Oink70** [comment]
This message typically shows when the chain has not synchronized past block 800200 yet.
Bootstrap your wallet: https://wiki.veruscoin.io/#!how-to/how-to_bootstrap.md
