### ISSUE TITLE
Bitcore (BCX) fails to connect in Lite mode

### ISSUE THREAD

**Issue by Oink70** [VerusCoin/Verus-Desktop#76]
Possibly the bitcore electrums have problems or changed protocol/servers/ports.
Reported in Discord and verified in my local Verus Desktop.
Possible electrum changes need investigating.

**Comment by michaeltout** [comment]
Seems to have resolved itself, appears it was an electrum issue. The report is much appreciated, but for future electrum issues, there isn't much we can do if the servers we are provided with for a coin don't work unless the devs of the coin contact us about it, so I'd prefer if potential server outages/connection issues were discussed outside of the GitHub issues page (unless of course it is clearly an issue with the wallet, not the servers).
