### ISSUE TITLE
download problems

### ISSUE THREAD

**Issue by chicco13** [VerusCoin/Verus-Desktop#77]
it downloads the wallet into finder but when I go to open it and it say developer is not verified

**Comment by Oink70** [comment]
A way to open a blocked app is to locate the app in a Finder window. 

1. Open the Finder.
2. Locate the app (it might be in the Applications folder, or it might still be in your downloads folder).
3. Ctrl-Click or right-click on the app.
4. Select Open from the resultant menu and the app will be opened anyway, and an exception will be created for opening it normally (i.e. by double-clicking) in future.

Alternatively you can disable this behavior by following this guide:
https://www.imore.com/how-open-apps-anywhere-macos-catalina-and-mojave

**Comment by chicco13** [comment]
hi thanks for your help one last thing how do I import my redfox lab coins to my Verus Mobile wallet
