### ISSUE TITLE
import from desktop to mobile

### ISSUE THREAD

**Issue by chicco13** [VerusCoin/Verus-Desktop#81]
hi how do I import my redfox coins in native mode  from my verus desktop wallet to my verus mobile wallet thanks and I can see my coins when I open my agama wallet. I see my redfox coins there also but won't let me send them

**Comment by michaeltout** [comment]
Hi, for questions relating to wallet use, please try asking on our community discord at https://discord.gg/VRKMP2S, if you notice a bug or issue with the wallet itself, feel free to report it here
