### ISSUE TITLE
Minor usability issue: In Windows Desktop wallet, keyboard shortcut to zoom in is set for EN/US keyboard layout

### ISSUE THREAD

**Issue by thoskk** [VerusCoin/Verus-Desktop#91]
![image](https://user-images.githubusercontent.com/61916028/109077424-6697e980-76fc-11eb-9442-6dce1a64003e.png)

as shown above, on German Windows 10, the advise for the shortcut is translated (English: CTRL+SHIFT+=), but the actual shortcut is different due to keyboard layout. In DE/DE layout, e.g., it's (translated) CTRL+SHIFT+* (keyboard, not number pad).

**Comment by michaeltout** [comment]
Huh thats strange, do other applications on the same machine get this right? I don't really have any control over the shortcut display in the electron framework that we use

**Comment by thoskk** [comment]
On another machine I have seen this being wrong in Outlook, too. But other software on this machine gets the settings right.
I suppose it's related to DE / EN keyboard layout difference.
