### ISSUE TITLE
Bootstrap script deprecation warning

### ISSUE THREAD

**Issue by alexenglish** [VerusCoin/Verus-Desktop#94]
A friend running the bootstrap script from Verus Desktop received this deprecation warning on a Windows 10 system.

![74152497-1423-46e4-a987-55de642d4703](https://user-images.githubusercontent.com/1755902/110708619-ccca4500-81af-11eb-8982-cdb7c24047e6.jpeg)

**Comment by michaeltout** [comment]
Since this was posted, bootstrap has been reworked and this should no longer occur.
